apiVersion: v1
kind: Service
metadata:
  name: tectonic-console-public
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 32000
      protocol: TCP
      name: tectonic-console-expose
  selector:
    tectonic-app: console
    tectonic-component: ui
