apiVersion: v1
kind: Service
metadata:
  labels:
    name: hygieia-ui-svc
  name: hygieia-ui-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    name: hygieia-ui
