apiVersion: v1
kind: ReplicationController
metadata:
 labels:
   name: mongo
 name: mongo-controller
spec:
 replicas: 1
 template:
   metadata:
     labels:
       name: mongo
   spec:
     containers:
     - image: mongo
       name: mongo
       ports:
       - name: mongo
         containerPort: 27017
       volumeMounts:
           - name: data
             mountPath: /data/db
     volumes:
        - name: data
          emptyDir: {}
